<?php 
    $title="Înregistrare domeniu website";
    $desc="Vă oferim servicii de înregistrare domenii site pentru afacerea ta";
    include "inc/header.php";
?>
    <section>
    <h1>Vânzare domenii website</h1>  
    <p>Vă oferim o gamă variată de extensii pentru site-ul dorit, ce pot fi achiziționate pentru o perioada de la 1 la 10 ani. </p>          
    <div class="domains">
        <div>
            <strong>.com</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.eu</strong>
            <span>8.50€</span>
        </div>
        <div>
            <strong>.net</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.biz</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.info</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.name</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.org</strong>
            <span>19.00€</span>
        </div>
        <div>
            <strong>.co</strong>
            <span>39.50€</span>
        </div>
        <div>
            <strong>.earth</strong>
            <span>36.00€</span>
        </div>
        <div>
            <strong>.shop</strong>
            <span>55.00€</span>
        </div>
        <div>
            <strong>.store</strong>
            <span>19.00€</span>
        </div>
        <div>
            <strong>.solutions</strong>
            <span>28.00€</span>
        </div>
        <div>
            <strong>.live</strong>
            <span>39.00€</span>
        </div>
        <div>
            <strong>.tech</strong>
            <span>15.50€</span>
        </div>
        <div>
            <strong>.pro</strong>
            <span>23.50€</span>
        </div>
        <div>
            <strong>.promo</strong>
            <span>31.00€</span>
        </div>
        <div>
            <strong>.property</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.film</strong>
            <span>132.00€</span>
        </div>
        <div>
            <strong>.studio</strong>
            <span>39.00€</span>
        </div>
        <div>
            <strong>.srl</strong>
            <span>61.50€</span>
        </div><div>
            <strong>.build</strong>
            <span>101.00€</span>
        </div>
        <div>
            <strong>.builders</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.sexy</strong>
            <span>28.00€</span>
        </div>
        <div>
            <strong>.cafe</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.camera</strong>
            <span>70.00€</span>
        </div>
        <div>
            <strong>.camp</strong>
            <span>70.00€</span>
        </div>
        <div>
            <strong>.capital</strong>
            <span>70.00€</span>
        </div>
        <div>
            <strong>.careers</strong>
            <span>70.00€</span>
        </div>
        <div>
            <strong>.casa</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.cash</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.catering</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.aero</strong>
            <span>78.50€</span>
        </div>
        <div>
            <strong>.agency</strong>
            <span>28.50€</span>
        </div>
        <div>
            <strong>.archi</strong>
            <span>94.00€</span>
        </div>        
        <div>
            <strong>.asia</strong>
            <span>23.50€</span>
        </div>
        <div>
            <strong>.audio</strong>
            <span>23.50€</span>
        </div>
        <div>
            <strong>.bar</strong>
            <span>101.00€</span>
        </div>
        <div>
            <strong>.bike</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.bio</strong>
            <span>95.50€</span>
        </div>
        <div>
            <strong>.blog</strong>
            <span>33.50€</span>
        </div>
        <div>
            <strong>.boutique</strong>
            <span>43.50€</span>
        </div>
        <div>
            <strong>.business</strong>
            <span>29.00€</span>
        </div>
        <div>
            <strong>.online</strong>
            <span>11.00€</span>
        </div>
    </div>                   
            
    </section>
<?php 
    include "inc/footer.php";
?>